modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="dimasctetracompat" #mandatory
version="${file.jarVersion}"
displayName="Dimensional Ascension Tetra Compat"
credits="I'd like to thank my adoring fans <3"
authors="ACCBDD"

description='''
Assorted Tetra effects and some mixins for compatibility and fun.
'''

[[dependencies.dimasctetracompat]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dimasctetracompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dimasctetracompat]]
    modId="blue_skies"
    mandatory=true
    versionRange="[1.3.20,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dimasctetracompat]]
    modId="tetra"
    mandatory=true
    versionRange="[5.6.0,)"
    ordering="AFTER"
    side="BOTH"
